<?php



use Illuminate\Database\Seeder;

class OrderDetailsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('order_details')->delete();
        
        \DB::table('order_details')->insert(array (
            0 => 
            array (
                'id' => 362,
                'order_id' => 199,
                'product_id' => 538,
                'price' => 60,
                'quantity' => 1,
                'discount' => 0,
                'total' => 150,
                'size' => 'M',
                'color' => 'slate lavender',
                'created_at' => '2020-07-16 18:38:44',
                'updated_at' => '2020-07-16 18:38:44',
            ),
            1 => 
            array (
                'id' => 363,
                'order_id' => 199,
                'product_id' => 539,
                'price' => 60,
                'quantity' => 1,
                'discount' => 0,
                'total' => 150,
                'size' => 'M',
                'color' => 'black',
                'created_at' => '2020-07-16 18:38:44',
                'updated_at' => '2020-07-16 18:38:44',
            ),
            2 => 
            array (
                'id' => 364,
                'order_id' => 199,
                'product_id' => 347,
                'price' => 30,
                'quantity' => 1,
                'discount' => 0,
                'total' => 150,
                'size' => 'XL',
                'color' => 'black marl',
                'created_at' => '2020-07-16 18:38:44',
                'updated_at' => '2020-07-16 18:38:44',
            ),
            3 => 
            array (
                'id' => 365,
                'order_id' => 200,
                'product_id' => 538,
                'price' => 60,
                'quantity' => 1,
                'discount' => 0,
                'total' => 150,
                'size' => 'M',
                'color' => 'slate lavender',
                'created_at' => '2020-07-16 18:39:54',
                'updated_at' => '2020-07-16 18:39:54',
            ),
            4 => 
            array (
                'id' => 366,
                'order_id' => 200,
                'product_id' => 539,
                'price' => 60,
                'quantity' => 1,
                'discount' => 0,
                'total' => 150,
                'size' => 'M',
                'color' => 'black',
                'created_at' => '2020-07-16 18:39:54',
                'updated_at' => '2020-07-16 18:39:54',
            ),
            5 => 
            array (
                'id' => 367,
                'order_id' => 200,
                'product_id' => 347,
                'price' => 30,
                'quantity' => 1,
                'discount' => 0,
                'total' => 150,
                'size' => 'XL',
                'color' => 'black marl',
                'created_at' => '2020-07-16 18:39:54',
                'updated_at' => '2020-07-16 18:39:54',
            ),
            6 => 
            array (
                'id' => 368,
                'order_id' => 201,
                'product_id' => 538,
                'price' => 60,
                'quantity' => 1,
                'discount' => 0,
                'total' => 150,
                'size' => 'M',
                'color' => 'slate lavender',
                'created_at' => '2020-07-16 19:27:50',
                'updated_at' => '2020-07-16 19:27:50',
            ),
            7 => 
            array (
                'id' => 369,
                'order_id' => 201,
                'product_id' => 539,
                'price' => 60,
                'quantity' => 1,
                'discount' => 0,
                'total' => 150,
                'size' => 'M',
                'color' => 'black',
                'created_at' => '2020-07-16 19:27:50',
                'updated_at' => '2020-07-16 19:27:50',
            ),
            8 => 
            array (
                'id' => 370,
                'order_id' => 201,
                'product_id' => 347,
                'price' => 30,
                'quantity' => 1,
                'discount' => 0,
                'total' => 150,
                'size' => 'XL',
                'color' => 'black marl',
                'created_at' => '2020-07-16 19:27:50',
                'updated_at' => '2020-07-16 19:27:50',
            ),
            9 => 
            array (
                'id' => 371,
                'order_id' => 202,
                'product_id' => 538,
                'price' => 60,
                'quantity' => 1,
                'discount' => 0,
                'total' => 150,
                'size' => 'M',
                'color' => 'slate lavender',
                'created_at' => '2020-07-16 19:56:00',
                'updated_at' => '2020-07-16 19:56:00',
            ),
            10 => 
            array (
                'id' => 372,
                'order_id' => 202,
                'product_id' => 539,
                'price' => 60,
                'quantity' => 1,
                'discount' => 0,
                'total' => 150,
                'size' => 'M',
                'color' => 'black',
                'created_at' => '2020-07-16 19:56:00',
                'updated_at' => '2020-07-16 19:56:00',
            ),
            11 => 
            array (
                'id' => 373,
                'order_id' => 202,
                'product_id' => 347,
                'price' => 30,
                'quantity' => 1,
                'discount' => 0,
                'total' => 150,
                'size' => 'XL',
                'color' => 'black marl',
                'created_at' => '2020-07-16 19:56:00',
                'updated_at' => '2020-07-16 19:56:00',
            ),
            12 => 
            array (
                'id' => 377,
                'order_id' => 204,
                'product_id' => 538,
                'price' => 60,
                'quantity' => 1,
                'discount' => 0,
                'total' => 450,
                'size' => 'M',
                'color' => 'slate lavender',
                'created_at' => '2020-07-19 11:26:17',
                'updated_at' => '2020-07-19 11:26:17',
            ),
            13 => 
            array (
                'id' => 378,
                'order_id' => 204,
                'product_id' => 347,
                'price' => 30,
                'quantity' => 1,
                'discount' => 0,
                'total' => 450,
                'size' => 'XL',
                'color' => 'black marl',
                'created_at' => '2020-07-19 11:26:17',
                'updated_at' => '2020-07-19 11:26:17',
            ),
            14 => 
            array (
                'id' => 379,
                'order_id' => 204,
                'product_id' => 205,
                'price' => 30,
                'quantity' => 3,
                'discount' => 0,
                'total' => 450,
                'size' => 'S',
                'color' => 'orange',
                'created_at' => '2020-07-19 11:26:17',
                'updated_at' => '2020-07-19 11:26:17',
            ),
            15 => 
            array (
                'id' => 380,
                'order_id' => 204,
                'product_id' => 418,
                'price' => 55,
                'quantity' => 3,
                'discount' => 0,
                'total' => 450,
                'size' => 'M',
                'color' => 'blue stone',
                'created_at' => '2020-07-19 11:26:17',
                'updated_at' => '2020-07-19 11:26:17',
            ),
            16 => 
            array (
                'id' => 381,
                'order_id' => 204,
                'product_id' => 42,
                'price' => 50,
                'quantity' => 1,
                'discount' => 0,
                'total' => 450,
                'size' => 'L',
                'color' => 'light blue',
                'created_at' => '2020-07-19 11:26:17',
                'updated_at' => '2020-07-19 11:26:17',
            ),
            17 => 
            array (
                'id' => 382,
                'order_id' => 204,
                'product_id' => 188,
                'price' => 55,
                'quantity' => 1,
                'discount' => 0,
                'total' => 450,
                'size' => 'XL',
                'color' => 'black',
                'created_at' => '2020-07-19 11:26:17',
                'updated_at' => '2020-07-19 11:26:17',
            ),
            18 => 
            array (
                'id' => 383,
                'order_id' => 205,
                'product_id' => 347,
                'price' => 30,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black marl',
                'created_at' => '2020-07-19 17:57:23',
                'updated_at' => '2020-07-19 17:57:23',
            ),
            19 => 
            array (
                'id' => 384,
                'order_id' => 205,
                'product_id' => 42,
                'price' => 50,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'L',
                'color' => 'light blue',
                'created_at' => '2020-07-19 17:57:23',
                'updated_at' => '2020-07-19 17:57:23',
            ),
            20 => 
            array (
                'id' => 385,
                'order_id' => 205,
                'product_id' => 188,
                'price' => 55,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black',
                'created_at' => '2020-07-19 17:57:23',
                'updated_at' => '2020-07-19 17:57:23',
            ),
            21 => 
            array (
                'id' => 386,
                'order_id' => 206,
                'product_id' => 347,
                'price' => 30,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black marl',
                'created_at' => '2020-08-07 18:17:12',
                'updated_at' => '2020-08-07 18:17:12',
            ),
            22 => 
            array (
                'id' => 387,
                'order_id' => 206,
                'product_id' => 42,
                'price' => 50,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'L',
                'color' => 'light blue',
                'created_at' => '2020-08-07 18:17:12',
                'updated_at' => '2020-08-07 18:17:12',
            ),
            23 => 
            array (
                'id' => 388,
                'order_id' => 206,
                'product_id' => 188,
                'price' => 55,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black',
                'created_at' => '2020-08-07 18:17:12',
                'updated_at' => '2020-08-07 18:17:12',
            ),
            24 => 
            array (
                'id' => 389,
                'order_id' => 207,
                'product_id' => 347,
                'price' => 30,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black marl',
                'created_at' => '2020-08-07 18:17:59',
                'updated_at' => '2020-08-07 18:17:59',
            ),
            25 => 
            array (
                'id' => 390,
                'order_id' => 207,
                'product_id' => 42,
                'price' => 50,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'L',
                'color' => 'light blue',
                'created_at' => '2020-08-07 18:17:59',
                'updated_at' => '2020-08-07 18:17:59',
            ),
            26 => 
            array (
                'id' => 391,
                'order_id' => 207,
                'product_id' => 188,
                'price' => 55,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black',
                'created_at' => '2020-08-07 18:17:59',
                'updated_at' => '2020-08-07 18:17:59',
            ),
            27 => 
            array (
                'id' => 392,
                'order_id' => 208,
                'product_id' => 347,
                'price' => 30,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black marl',
                'created_at' => '2020-08-07 18:23:43',
                'updated_at' => '2020-08-07 18:23:43',
            ),
            28 => 
            array (
                'id' => 393,
                'order_id' => 208,
                'product_id' => 42,
                'price' => 50,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'L',
                'color' => 'light blue',
                'created_at' => '2020-08-07 18:23:43',
                'updated_at' => '2020-08-07 18:23:43',
            ),
            29 => 
            array (
                'id' => 394,
                'order_id' => 208,
                'product_id' => 188,
                'price' => 55,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black',
                'created_at' => '2020-08-07 18:23:43',
                'updated_at' => '2020-08-07 18:23:43',
            ),
            30 => 
            array (
                'id' => 395,
                'order_id' => 209,
                'product_id' => 347,
                'price' => 30,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black marl',
                'created_at' => '2020-08-07 18:26:31',
                'updated_at' => '2020-08-07 18:26:31',
            ),
            31 => 
            array (
                'id' => 396,
                'order_id' => 209,
                'product_id' => 42,
                'price' => 50,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'L',
                'color' => 'light blue',
                'created_at' => '2020-08-07 18:26:31',
                'updated_at' => '2020-08-07 18:26:31',
            ),
            32 => 
            array (
                'id' => 397,
                'order_id' => 209,
                'product_id' => 188,
                'price' => 55,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black',
                'created_at' => '2020-08-07 18:26:31',
                'updated_at' => '2020-08-07 18:26:31',
            ),
            33 => 
            array (
                'id' => 398,
                'order_id' => 210,
                'product_id' => 347,
                'price' => 30,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black marl',
                'created_at' => '2020-08-07 18:27:09',
                'updated_at' => '2020-08-07 18:27:09',
            ),
            34 => 
            array (
                'id' => 399,
                'order_id' => 210,
                'product_id' => 42,
                'price' => 50,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'L',
                'color' => 'light blue',
                'created_at' => '2020-08-07 18:27:09',
                'updated_at' => '2020-08-07 18:27:09',
            ),
            35 => 
            array (
                'id' => 400,
                'order_id' => 210,
                'product_id' => 188,
                'price' => 55,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black',
                'created_at' => '2020-08-07 18:27:09',
                'updated_at' => '2020-08-07 18:27:09',
            ),
            36 => 
            array (
                'id' => 401,
                'order_id' => 211,
                'product_id' => 347,
                'price' => 30,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black marl',
                'created_at' => '2020-08-07 18:28:38',
                'updated_at' => '2020-08-07 18:28:38',
            ),
            37 => 
            array (
                'id' => 402,
                'order_id' => 211,
                'product_id' => 42,
                'price' => 50,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'L',
                'color' => 'light blue',
                'created_at' => '2020-08-07 18:28:38',
                'updated_at' => '2020-08-07 18:28:38',
            ),
            38 => 
            array (
                'id' => 403,
                'order_id' => 211,
                'product_id' => 188,
                'price' => 55,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black',
                'created_at' => '2020-08-07 18:28:38',
                'updated_at' => '2020-08-07 18:28:38',
            ),
            39 => 
            array (
                'id' => 404,
                'order_id' => 212,
                'product_id' => 347,
                'price' => 30,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black marl',
                'created_at' => '2020-08-07 18:33:19',
                'updated_at' => '2020-08-07 18:33:19',
            ),
            40 => 
            array (
                'id' => 405,
                'order_id' => 212,
                'product_id' => 42,
                'price' => 50,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'L',
                'color' => 'light blue',
                'created_at' => '2020-08-07 18:33:19',
                'updated_at' => '2020-08-07 18:33:19',
            ),
            41 => 
            array (
                'id' => 406,
                'order_id' => 212,
                'product_id' => 188,
                'price' => 55,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black',
                'created_at' => '2020-08-07 18:33:19',
                'updated_at' => '2020-08-07 18:33:19',
            ),
            42 => 
            array (
                'id' => 407,
                'order_id' => 213,
                'product_id' => 347,
                'price' => 30,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black marl',
                'created_at' => '2020-08-07 18:36:50',
                'updated_at' => '2020-08-07 18:36:50',
            ),
            43 => 
            array (
                'id' => 408,
                'order_id' => 213,
                'product_id' => 42,
                'price' => 50,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'L',
                'color' => 'light blue',
                'created_at' => '2020-08-07 18:36:50',
                'updated_at' => '2020-08-07 18:36:50',
            ),
            44 => 
            array (
                'id' => 409,
                'order_id' => 213,
                'product_id' => 188,
                'price' => 55,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black',
                'created_at' => '2020-08-07 18:36:50',
                'updated_at' => '2020-08-07 18:36:50',
            ),
            45 => 
            array (
                'id' => 410,
                'order_id' => 214,
                'product_id' => 347,
                'price' => 30,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black marl',
                'created_at' => '2020-08-07 18:37:20',
                'updated_at' => '2020-08-07 18:37:20',
            ),
            46 => 
            array (
                'id' => 411,
                'order_id' => 214,
                'product_id' => 42,
                'price' => 50,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'L',
                'color' => 'light blue',
                'created_at' => '2020-08-07 18:37:20',
                'updated_at' => '2020-08-07 18:37:20',
            ),
            47 => 
            array (
                'id' => 412,
                'order_id' => 214,
                'product_id' => 188,
                'price' => 55,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black',
                'created_at' => '2020-08-07 18:37:20',
                'updated_at' => '2020-08-07 18:37:20',
            ),
            48 => 
            array (
                'id' => 413,
                'order_id' => 215,
                'product_id' => 347,
                'price' => 30,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black marl',
                'created_at' => '2020-08-07 18:38:10',
                'updated_at' => '2020-08-07 18:38:10',
            ),
            49 => 
            array (
                'id' => 414,
                'order_id' => 215,
                'product_id' => 42,
                'price' => 50,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'L',
                'color' => 'light blue',
                'created_at' => '2020-08-07 18:38:10',
                'updated_at' => '2020-08-07 18:38:10',
            ),
            50 => 
            array (
                'id' => 415,
                'order_id' => 215,
                'product_id' => 188,
                'price' => 55,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black',
                'created_at' => '2020-08-07 18:38:10',
                'updated_at' => '2020-08-07 18:38:10',
            ),
            51 => 
            array (
                'id' => 416,
                'order_id' => 216,
                'product_id' => 347,
                'price' => 30,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black marl',
                'created_at' => '2020-08-07 18:40:01',
                'updated_at' => '2020-08-07 18:40:01',
            ),
            52 => 
            array (
                'id' => 417,
                'order_id' => 216,
                'product_id' => 42,
                'price' => 50,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'L',
                'color' => 'light blue',
                'created_at' => '2020-08-07 18:40:02',
                'updated_at' => '2020-08-07 18:40:02',
            ),
            53 => 
            array (
                'id' => 418,
                'order_id' => 216,
                'product_id' => 188,
                'price' => 55,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black',
                'created_at' => '2020-08-07 18:40:03',
                'updated_at' => '2020-08-07 18:40:03',
            ),
            54 => 
            array (
                'id' => 419,
                'order_id' => 217,
                'product_id' => 347,
                'price' => 30,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black marl',
                'created_at' => '2020-08-07 18:44:41',
                'updated_at' => '2020-08-07 18:44:41',
            ),
            55 => 
            array (
                'id' => 420,
                'order_id' => 217,
                'product_id' => 42,
                'price' => 50,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'L',
                'color' => 'light blue',
                'created_at' => '2020-08-07 18:44:41',
                'updated_at' => '2020-08-07 18:44:41',
            ),
            56 => 
            array (
                'id' => 421,
                'order_id' => 217,
                'product_id' => 188,
                'price' => 55,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black',
                'created_at' => '2020-08-07 18:44:41',
                'updated_at' => '2020-08-07 18:44:41',
            ),
            57 => 
            array (
                'id' => 422,
                'order_id' => 218,
                'product_id' => 347,
                'price' => 30,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black marl',
                'created_at' => '2020-08-07 18:46:24',
                'updated_at' => '2020-08-07 18:46:24',
            ),
            58 => 
            array (
                'id' => 423,
                'order_id' => 218,
                'product_id' => 42,
                'price' => 50,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'L',
                'color' => 'light blue',
                'created_at' => '2020-08-07 18:46:24',
                'updated_at' => '2020-08-07 18:46:24',
            ),
            59 => 
            array (
                'id' => 424,
                'order_id' => 218,
                'product_id' => 188,
                'price' => 55,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black',
                'created_at' => '2020-08-07 18:46:24',
                'updated_at' => '2020-08-07 18:46:24',
            ),
            60 => 
            array (
                'id' => 425,
                'order_id' => 219,
                'product_id' => 347,
                'price' => 30,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black marl',
                'created_at' => '2020-08-07 18:48:20',
                'updated_at' => '2020-08-07 18:48:20',
            ),
            61 => 
            array (
                'id' => 426,
                'order_id' => 219,
                'product_id' => 42,
                'price' => 50,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'L',
                'color' => 'light blue',
                'created_at' => '2020-08-07 18:48:20',
                'updated_at' => '2020-08-07 18:48:20',
            ),
            62 => 
            array (
                'id' => 427,
                'order_id' => 219,
                'product_id' => 188,
                'price' => 55,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black',
                'created_at' => '2020-08-07 18:48:20',
                'updated_at' => '2020-08-07 18:48:20',
            ),
            63 => 
            array (
                'id' => 428,
                'order_id' => 220,
                'product_id' => 347,
                'price' => 30,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black marl',
                'created_at' => '2020-08-07 18:50:08',
                'updated_at' => '2020-08-07 18:50:08',
            ),
            64 => 
            array (
                'id' => 429,
                'order_id' => 220,
                'product_id' => 42,
                'price' => 50,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'L',
                'color' => 'light blue',
                'created_at' => '2020-08-07 18:50:08',
                'updated_at' => '2020-08-07 18:50:08',
            ),
            65 => 
            array (
                'id' => 430,
                'order_id' => 220,
                'product_id' => 188,
                'price' => 55,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black',
                'created_at' => '2020-08-07 18:50:08',
                'updated_at' => '2020-08-07 18:50:08',
            ),
            66 => 
            array (
                'id' => 431,
                'order_id' => 221,
                'product_id' => 347,
                'price' => 30,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black marl',
                'created_at' => '2020-08-07 18:50:36',
                'updated_at' => '2020-08-07 18:50:36',
            ),
            67 => 
            array (
                'id' => 432,
                'order_id' => 221,
                'product_id' => 42,
                'price' => 50,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'L',
                'color' => 'light blue',
                'created_at' => '2020-08-07 18:50:36',
                'updated_at' => '2020-08-07 18:50:36',
            ),
            68 => 
            array (
                'id' => 433,
                'order_id' => 221,
                'product_id' => 188,
                'price' => 55,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black',
                'created_at' => '2020-08-07 18:50:36',
                'updated_at' => '2020-08-07 18:50:36',
            ),
            69 => 
            array (
                'id' => 434,
                'order_id' => 222,
                'product_id' => 347,
                'price' => 30,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black marl',
                'created_at' => '2020-08-07 18:51:01',
                'updated_at' => '2020-08-07 18:51:01',
            ),
            70 => 
            array (
                'id' => 435,
                'order_id' => 222,
                'product_id' => 42,
                'price' => 50,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'L',
                'color' => 'light blue',
                'created_at' => '2020-08-07 18:51:01',
                'updated_at' => '2020-08-07 18:51:01',
            ),
            71 => 
            array (
                'id' => 436,
                'order_id' => 222,
                'product_id' => 188,
                'price' => 55,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black',
                'created_at' => '2020-08-07 18:51:01',
                'updated_at' => '2020-08-07 18:51:01',
            ),
            72 => 
            array (
                'id' => 437,
                'order_id' => 223,
                'product_id' => 347,
                'price' => 30,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black marl',
                'created_at' => '2020-08-07 19:08:22',
                'updated_at' => '2020-08-07 19:08:22',
            ),
            73 => 
            array (
                'id' => 438,
                'order_id' => 223,
                'product_id' => 42,
                'price' => 50,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'L',
                'color' => 'light blue',
                'created_at' => '2020-08-07 19:08:22',
                'updated_at' => '2020-08-07 19:08:22',
            ),
            74 => 
            array (
                'id' => 439,
                'order_id' => 223,
                'product_id' => 188,
                'price' => 55,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black',
                'created_at' => '2020-08-07 19:08:22',
                'updated_at' => '2020-08-07 19:08:22',
            ),
            75 => 
            array (
                'id' => 440,
                'order_id' => 224,
                'product_id' => 347,
                'price' => 30,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black marl',
                'created_at' => '2020-08-07 19:08:52',
                'updated_at' => '2020-08-07 19:08:52',
            ),
            76 => 
            array (
                'id' => 441,
                'order_id' => 224,
                'product_id' => 42,
                'price' => 50,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'L',
                'color' => 'light blue',
                'created_at' => '2020-08-07 19:08:52',
                'updated_at' => '2020-08-07 19:08:52',
            ),
            77 => 
            array (
                'id' => 442,
                'order_id' => 224,
                'product_id' => 188,
                'price' => 55,
                'quantity' => 1,
                'discount' => 0,
                'total' => 135,
                'size' => 'XL',
                'color' => 'black',
                'created_at' => '2020-08-07 19:08:52',
                'updated_at' => '2020-08-07 19:08:52',
            ),
            78 => 
            array (
                'id' => 443,
                'order_id' => 225,
                'product_id' => 1,
                'price' => 40,
                'quantity' => 1,
                'discount' => 0,
                'total' => 40,
                'size' => 'M',
                'color' => 'black',
                'created_at' => '2020-09-04 04:21:25',
                'updated_at' => '2020-09-04 04:21:25',
            ),
            79 => 
            array (
                'id' => 444,
                'order_id' => 226,
                'product_id' => 1,
                'price' => 40,
                'quantity' => 1,
                'discount' => 0,
                'total' => 40,
                'size' => 'M',
                'color' => 'black',
                'created_at' => '2020-09-04 04:22:50',
                'updated_at' => '2020-09-04 04:22:50',
            ),
            80 => 
            array (
                'id' => 445,
                'order_id' => 227,
                'product_id' => 1,
                'price' => 40,
                'quantity' => 1,
                'discount' => 0,
                'total' => 40,
                'size' => 'M',
                'color' => 'black',
                'created_at' => '2020-09-04 04:30:22',
                'updated_at' => '2020-09-04 04:30:22',
            ),
        ));
        
        
    }
}